# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'GGActionSheetDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

  # Pods for GGActionSheetDemo
    
    pod 'Masonry','~> 0.6.3'

end
